name: 🚀 Publish new version
# Run this on every push to master and next
on:
  push:
    branches:
      - master
      - next

env:
  HUSKY: 0

jobs:
  publish:
    # Use the latest version of Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      # Checkout repository
      - name: 📥 Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # Setup Node
      - name: 📦 Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc

      # Enable corepack
      - name: ⚙️ Enable corepack
        run: corepack enable && corepack enable npm

      # Install dependencies
      - name: 📦 Install dependencies
        run: npm ci

      # Check format
      - name: 🧹 Check format
        run: npm run format:check

      # Create release
      - name: 🚀 Create release
        if: github.repository == 'pawcoding/markdown-mcp-resource'
        id: release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        with:
          semantic_version: 25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
